Repository 4linethon12/backend, pull requests merged in 2024-11, with the labels that each got.

#4 Feature/login
  project/project/settings.py
  project/requirements.txt
  project/users/models.py
  project/users/serializers.py
  project/users/urls.py
  project/users/views.py
Labels: feature

#9 Chore/swagger
  project/groups/serializers.py
  project/project/settings.py
  project/project/urls.py
  project/requirements.txt
  project/users/views.py
Labels: chore

#7 Feature/refresh
  project/project/settings.py
  project/users/serializers.py
  project/users/views.py
Labels: feature

#10 Feature/manito match
  project/groups/urls.py
  project/manito/serializers.py
  project/manito/views.py
  project/project/settings.py
  project/requirements.txt
  project/users/models.py
  project/users/views.py
Labels: feature

#11 Feature/group
  project/groups/models.py
  project/groups/serializers.py
  project/groups/urls.py
  project/groups/views.py
  project/requirements.txt
Labels: feature

#14 Chore/manito
  project/groups/migrations/0003_groupparticipant.py
  project/manito/admin.py
  project/users/migrations/0002_user_date_joined_user_email_user_first_name_and_more.py
Labels: chore

#13 Chore/group,user
  project/groups/admin.py
  project/groups/urls.py
  project/groups/views.py
  project/users/admin.py
Labels: chore

#15 feature/group
  project/groups/views.py
Labels: feature

#16 feature/group
  project/groups/urls.py
Labels: feature

#17 Chore/decorator
  project/groups/migrations/0001_initial.py
  project/groups/migrations/0002_recommendedmission_group_group_leader_group_mission_and_more.py
  project/groups/migrations/0003_groupparticipant.py
  project/groups/views.py
  project/manito/migrations/0001_initial.py
  project/manito/views.py
  project/project/settings.py
  project/users/migrations/0001_initial.py
  project/users/migrations/0002_user_date_joined_user_email_user_first_name_and_more.py
Labels: chore

#20 Chore/add decorator
  project/groups/views.py
  project/manito/serializers.py
  project/manito/views.py
  project/users/serializers.py
  project/users/views.py
Labels: chore

#23 Chore/plus decorator
  project/groups/serializers.py
  project/groups/views.py
  project/manito/views.py
Labels: chore

#25 feature: matches 추가
  project/groups/serializers.py
Labels: feature

#26 Feature/group
  project/groups/migrations/0001_initial.py
  project/manito/migrations/0001_initial.py
  project/manito/migrations/0002_remove_manitomessage_giver_and_more.py
  project/manito/models.py
  project/manito/urls.py
  project/manito/views.py
  project/users/migrations/0002_user_date_joined_user_email_user_first_name_and_more.py
Labels: feature

#28 feature: 데코레이터설정, 로직 픽스, receiver 기준 그룹 아이디 추가
  project/manito/views.py
Labels: feature

#30 fix: migrations fix
  project/groups/migrations/0001_initial.py
  project/manito/migrations/0001_initial.py
  project/manito/migrations/0002_remove_manitomessage_giver_and_more.py
  project/users/migrations/0001_initial.py
  project/users/migrations/0002_user_date_joined_user_email_user_first_name_and_more.py
Labels: fix

#32 fix: 페이지네이션 제거
  project/groups/views.py
  project/manito/views.py
  project/users/views.py
Labels: fix

#35 Feature/group
  project/groups/models.py
  project/groups/serializers.py
  project/groups/views.py
Labels: feature, fix

#34 fix: 메시지 생성 오류 수정
  project/manito/views.py
Labels: fix

#37 refactor: 그룹 생성 body 수정
  project/groups/views.py
  project/users/views.py
Labels: refactor
